version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: civic
      POSTGRES_PASSWORD: civic
      POSTGRES_DB: civicstack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://civic:civic@db:5432/civicstack
      - ADMIN_PASSWORD=ChangeMeNow

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
